kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    username: justmiles
    password: 
      from_secret: docker_password
    repo: justmiles/carapace
    tags: latest
    squash: true
    auto_tag: true
    environment:
      DOCKER_BUILDKIT: "1"
    cache_from:
      - "justmiles/carapace:latest"
