kind: pipeline
name: default

steps:
- name: prepare-tags
  image: alpine
  commands:
  - export OPENCLAW_VER=$(grep "ENV GITHUB_RELEASE_OPENCLAW__OPENCLAW=" Dockerfile | cut -d= -f2)
  - |
    if [ -n "$DRONE_TAG" ]; then
      echo -n "latest,${DRONE_TAG},${DRONE_TAG}-openclaw-${OPENCLAW_VER}" > .tags
    else
      echo -n "latest" > .tags
    fi

- name: docker
  image: plugins/docker
  settings:
    username: justmiles
    password: 
      from_secret: docker_password
    repo: justmiles/carapace
    squash: true
    cache_from:
      - "justmiles/carapace:latest"
