kind: pipeline
name: default

steps:
- name: prepare-tags
  image: alpine/git
  commands:
  - |
    git fetch --tags
    git tag --sort=-v:refname
    export OPENCLAW_VER=$(grep "ENV GITHUB_RELEASE_OPENCLAW__OPENCLAW=" Dockerfile | cut -d= -f2 | awk '{print $1}')
    export LATEST_TAG=$(git tag --sort=-v:refname | head -n 1)
    echo -n "latest,$LATEST_TAG,$LATEST_TAG-openclaw-$OPENCLAW_VER" > .tags
    if [ -n "$DRONE_VERSION" ]; then echo -n ",$DRONE_VERSION" >> .tags; fi
    cat .tags

- name: docker
  image: plugins/docker
  settings:
    username: justmiles
    password: 
      from_secret: docker_password
    repo: justmiles/carapace
    squash: false
    cache_from:
      - "justmiles/carapace:latest"

trigger:
  branch:
  - main
  event:
  - push
