#!/command/with-contenv bash

# Create /tmp/.X11-unix if it does not exist
if [ ! -d /tmp/.X11-unix ]; then
  mkdir -p /tmp/.X11-unix
  chmod 1777 /tmp/.X11-unix
fi

exec s6-setuidgid openclaw /etc/s6-overlay/s6-rc.d/display/scripts/display.sh 2>&1 >> /var/log/display
